### ISSUE TITLE
api\index.spec.js fails

### ISSUE THREAD

**Issue by fresheneesz** [LN-Zap/zap-desktop#1]
When I ran `npm run test`, it tells me I need to run a couple other things. `npm run build-main` seemed to work fine, and `npm run build-renderer` took a long time, but ended up working. But after that, when I run the tests, all of them pass except `api\index.spec.js`:

```
C:\zap\zap-desktop>npm run test

> zap-desktop@0.0.1 test C:\zap\zap-desktop
> cross-env NODE_ENV=test BABEL_DISABLE_CACHE=1 node --trace-warnings ./test/runTests.js

 PASS  test\reducers\form.spec.js
 PASS  test\reducers\info.spec.js
 PASS  test\reducers\balance.spec.js
 PASS  test\reducers\payment.spec.js
 PASS  test\reducers\channels.spec.js
 PASS  test\reducers\invoice.spec.js
 PASS  test\reducers\ticker.spec.js
 PASS  test\reducers\peers.spec.js
 FAIL  test\api\index.spec.js (10.795s)
  ? API > getinfo > is synced to the chain

    TypeError: Cannot read property 'synced_to_chain' of undefined

      at Object.<anonymous> (test/api/index.spec.js:7:23)
          at Generator.next (<anonymous>)
      at step (test/api/index.spec.js:1:323)
      at test/api/index.spec.js:1:483
      at process._tickCallback (internal/process/next_tick.js:109:7)

  ? API > getinfo > only supports 1 chain at a time

    TypeError: Cannot read property 'chains' of undefined

      at Object.<anonymous> (test/api/index.spec.js:12:23)
          at Generator.next (<anonymous>)
      at step (test/api/index.spec.js:1:323)
      at test/api/index.spec.js:1:483
      at process._tickCallback (internal/process/next_tick.js:109:7)

  ? API > balance > returns wallet balance

    TypeError: Cannot read property 'balance' of undefined

      at Object.<anonymous> (test/api/index.spec.js:19:41)
          at Generator.next (<anonymous>)
      at step (test/api/index.spec.js:1:323)
      at test/api/index.spec.js:1:483
      at process._tickCallback (internal/process/next_tick.js:109:7)

  ? API > balance > returns channel balance

    TypeError: Cannot read property 'balance' of undefined

      at Object.<anonymous> (test/api/index.spec.js:24:42)
          at Generator.next (<anonymous>)
      at step (test/api/index.spec.js:1:323)
      at test/api/index.spec.js:1:483
      at process._tickCallback (internal/process/next_tick.js:109:7)

  ? API > peers > peers is an array

    TypeError: Cannot read property 'peers' of undefined

      at Object.<anonymous> (test/api/index.spec.js:31:38)
          at Generator.next (<anonymous>)
      at step (test/api/index.spec.js:1:323)
      at test/api/index.spec.js:1:483
      at process._tickCallback (internal/process/next_tick.js:109:7)

  ? API > channels > channels is an array

    TypeError: Cannot read property 'channels' of undefined

      at Object.<anonymous> (test/api/index.spec.js:38:41)
          at Generator.next (<anonymous>)
      at step (test/api/index.spec.js:1:323)
      at test/api/index.spec.js:1:483
      at process._tickCallback (internal/process/next_tick.js:109:7)

  ? API > invoices > invoices is an array

    TypeError: Cannot read property 'invoices' of undefined

      at Object.<anonymous> (test/api/index.spec.js:45:41)
          at Generator.next (<anonymous>)
      at step (test/api/index.spec.js:1:323)
      at test/api/index.spec.js:1:483
      at process._tickCallback (internal/process/next_tick.js:109:7)

  ? API > payments > payments is an array

    TypeError: Cannot read property 'payments' of undefined

      at Object.<anonymous> (test/api/index.spec.js:52:41)
          at Generator.next (<anonymous>)
      at step (test/api/index.spec.js:1:323)
      at test/api/index.spec.js:1:483
      at process._tickCallback (internal/process/next_tick.js:109:7)

Test Suites: 1 failed, 8 passed, 9 total
Tests:       8 failed, 94 passed, 102 total
Snapshots:   51 passed, 51 total
Time:        12.811s
Ran all test suites matching "test\\(?!e2e\\)[^\\]+\\.+\.spec\.js$".
```

I'm on a windows 8.1 machine with node v7.10.0

**Comment by jackmallers** [comment]
Hm, interesting. The API tests failed, which means something is up with the nodejs repo or your BTCD/LND.

Do you have BTCD, LND and zap-nodejs up and running?

**Comment by fresheneesz** [comment]
Oh I didn't have either the bitcoin daemon or the LN daemon up. My ad-blindness made me miss that greyed out note in the readme. The only requirements I payed attention to are the bolded bullet points. I'll edit the readme to be a bit more consistent in how requirements are listed.

**Comment by fresheneesz** [comment]
https://github.com/LN-Zap/zap-desktop/pull/3

**Comment by fresheneesz** [comment]
I suppose there should be something it does to detect which requirement isn't available and properly report this in the test
