### ISSUE TITLE
"Object has been destroyed" Javascript error when quitting app on Ubuntu

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#1053]
## Description

On windows / ubuntu we get the following error sometimes when quitting the app:
```
Uncaught Exception:
Error: Object has been destroyed
    at BrowserWindow.send (/opt/ZapDesktop/resources/electron.asar/browser/api/browser-window.js:179:17)
    at ClientReadableStream.e.on.e (/opt/ZapDesktop/resources/app.asar/webpack:/app/lib/lnd/subscribe/channelgraph.js:14:11)
    at emitOne (events.js:116:13)
    at ClientReadableStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientReadableStream.Readable.push (_stream_readable.js:208:10)
    at Object.onReceiveMessage (/opt/ZapDesktop/resources/app.asar/node_modules/grpc/src/client_interceptors.js:1242:19)
    at InterceptingListener.recvMessageWithContext (/opt/ZapDesktop/resources/app.asar/node_modules/grpc/src/client_interceptors.js:603:19)
    at /opt/ZapDesktop/resources/app.asar/node_modules/grpc/src/client_interceptors.js:702:14
```

Error looks similar to #677 

## Expected Behavior

Should not give this error.

## Actual Behavior

Gives the error

## Your Environment

- Zap Desktop version: 0.2.2
- Operating System and version: Ubuntu

Reported by Leo in Slack

**Comment by Liongrass** [comment]
```DEBUG_LEVEL=debug DEBUG=zap /usr/local/bin/zap-desktop 
flow-runtime: Cannot resolve type: Event
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.```

The `flow-runtime` log comes up at startup, the `gtk-message` comes together with the javascript error

**Comment by Liongrass** [comment]
```  zap:main   closed_chans: [] } +13s
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
  zap:main [ERR]  describeGraph: Error: Object has been destroyed
  zap:main ___Stack trace #1___
  zap:main Error: Object has been destroyed
  zap:main     at WebContents.send (/opt/ZapDesktop/resources/electron.asar/browser/api/web-contents.js:100:15)
  zap:main     at l.describeGraph.then.e (/opt/ZapDesktop/resources/app.asar/webpack:/app/lib/lnd/methods/index.js:39:10)
  zap:main     at <anonymous> +17s
```

**Comment by bhide-fr** [comment]
Doesn't reproduce in Mint 18 after upgrade to 0.3.2-beta
