### ISSUE TITLE
Error: unknown service lnrpc.Lightning

### ISSUE THREAD

**Issue by Zubin-Teherani** [LN-Zap/zap-desktop#125]
I'm getting the following error while trying to run `npm run dev` while running lnd:
```
[0] error:  { Error: unknown service lnrpc.Lightning
[0]     at ClientReadableStream._emitStatusIfDone (/Users/zubin/open_source/zap-desktop/app/node_modules/grpc/src/client.js:255:19)
[0]     at ClientReadableStream._receiveStatus (/Users/zubin/open_source/zap-desktop/app/node_modules/grpc/src/client.js:233:8)
[0]     at /Users/zubin/open_source/zap-desktop/app/node_modules/grpc/src/client.js:705:12 code: 12, metadata: Metadata { _internal_repr: {} } }
[0] TRANSACTION STATUS:  { code: 12,
[0]   details: 'unknown service lnrpc.Lightning',
[0]   metadata: Metadata { _internal_repr: {} } }
```

**Comment by joaodealmeida** [comment]
May I know the OS?

Did you install grpc ?

**Comment by Zubin-Teherani** [comment]
@joaodealmeida this was fixed with the help of @janis in the slack channel. 

I think I was running lnd wrong. I moved the binary to the resources folder and this fixed my problems. Going to close this issue now.

Looking forward to trying to help here!
