### ISSUE TITLE
IBUS-WARNING

### ISSUE THREAD

**Issue by callmekurisu** [LN-Zap/zap-desktop#13]
On Ubuntu 16.04 after 'npm run dev':

`(electron:7538): IBUS-WARNING **: Unable to connect to ibus: Could not connect: Connection refused
(node:7504) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
    at /home/kurisu/zap-desktop/node_modules/extract-text-webpack-plugin/index.js:271:24
    at /home/kurisu/zap-desktop/node_modules/async/dist/async.js:3060:16
    at eachOfArrayLike (/home/kurisu/zap-desktop/node_modules/async/dist/async.js:1003:9)
    at eachOf (/home/kurisu/zap-desktop/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/home/kurisu/zap-desktop/node_modules/async/dist/async.js:3122:5)
    at ExtractTextPlugin.<anonymous> (/home/kurisu/zap-desktop/node_modules/extract-text-webpack-plugin/index.js:268:10)
    at Compilation.applyPluginsAsyncSeries (/home/kurisu/zap-desktop/node_modules/tapable/lib/Tapable.js:142:13)
    at Compilation.seal (/home/kurisu/zap-desktop/node_modules/webpack/lib/Compilation.js:580:8)
    at /home/kurisu/zap-desktop/node_modules/webpack/lib/Compiler.js:510:16
    at /home/kurisu/zap-desktop/node_modules/tapable/lib/Tapable.js:225:11
balance error:  { Error: expected 1 macaroon, got 0
    at /home/kurisu/zap-desktop/node_modules/grpc/src/node/src/client.js:554:15 code: 2, metadata: Metadata { _internal_repr: {} } }
payments error:  { Error: expected 1 macaroon, got 0
    at /home/kurisu/zap-desktop/node_modules/grpc/src/node/src/client.js:554:15 code: 2, metadata: Metadata { _internal_repr: {} } }
invoices error:  { Error: expected 1 macaroon, got 0
    at /home/kurisu/zap-desktop/node_modules/grpc/src/node/src/client.js:554:15 code: 2, metadata: Metadata { _internal_repr: {} } }`

**Comment by jackmallers** [comment]
Do you have you run `./node_modules/.bin/electron-rebuild` and do you have `LND` running?

**Comment by callmekurisu** [comment]
Yes LND is running 

`
2017-08-29 22:09:18.156 [WRN] LTND: open /home/kurisu/.lnd/lnd.conf: no such file or directory
2017-08-29 22:09:18.156 [INF] LTND: Version 0.3.0-alpha
2017-08-29 22:09:18.156 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
2017-08-29 22:09:18.159 [INF] LTND: Primary chain is set to: bitcoin
2017-08-29 22:09:18.980 [INF] LNWL: Opened wallet
2017-08-29 22:09:19.020 [INF] LNWL: Established connection to RPC server localhost:18334
2017-08-29 22:09:19.916 [INF] LNWL: The wallet has been unlocked without a time limit
2017-08-29 22:09:19.916 [INF] LNWL: Catching up block hashes to height 1180518, this will take a while...
2017-08-29 22:09:19.920 [INF] LTND: LightningWallet opened
2017-08-29 22:09:19.943 [INF] RPCS: gRPC proxy started at localhost:8080
2017-08-29 22:09:19.943 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2017-08-29 22:09:19.943 [INF] LTND: Waiting for chain backend to finish sync, start_height=1180518
`

`2017-08-29 22:12:00.867 [INF] LNWL: Done catching up block hashes
2017-08-29 22:12:00.869 [INF] LNWL: Started rescan from block 000000000000069d79fc4a599dff2c8b9152813b469b49d856b86ad9a23cd402 (height 1180518) for 0 addresses
2017-08-29 22:12:00.870 [INF] LNWL: Finished rescan for 0 addresses (synced to block 000000000000069d79fc4a599dff2c8b9152813b469b49d856b86ad9a23cd402, height 1180518)
2017-08-29 22:12:00.870 [INF] LNWL: Catching up block hashes to height 1180518, this might take a while
2017-08-29 22:12:00.872 [INF] LNWL: Done catching up block hashes
2017-08-29 22:12:01.028 [INF] LTND: Chain backend is fully synced (end_height=1180518)!
2017-08-29 22:12:01.072 [INF] LNWL: Established connection to RPC server localhost:18334
2017-08-29 22:12:01.072 [INF] HSWC: Starting HTLC Switch
2017-08-29 22:12:01.072 [INF] NTFN: New block epoch subscription
2017-08-29 22:12:01.073 [INF] DISC: Authenticated Gossiper is starting
2017-08-29 22:12:01.073 [INF] NTFN: New block epoch subscription
2017-08-29 22:12:01.073 [INF] CRTR: FilteredChainView starting
2017-08-29 22:12:01.114 [INF] LNWL: Established connection to RPC server localhost:18334
2017-08-29 22:12:01.115 [INF] CRTR: Prune tip for Channel Graph: height=1180518, hash=000000000000069d79fc4a599dff2c8b9152813b469b49d856b86ad9a23cd402
2017-08-29 22:12:01.115 [INF] CRTR: Filtering chain using 0 channels active
2017-08-29 22:12:01.115 [DBG] CRTR: Updating chain filter with new UTXO's: []
2017-08-29 22:12:01.115 [INF] CMGR: Server listening on [::]:9735
`

**Comment by callmekurisu** [comment]
Ahh! I ran with --no-macaroons and it works!!

**Comment by MasterNeuron** [comment]
"Ahh! I ran with --no-macaroons and it works!!" - This is not the best practice...
