### ISSUE TITLE
invalid passphrase for master public key

### ISSUE THREAD

**Issue by mariodian** [LN-Zap/zap-desktop#141]
When I run `npm run dev` the app is stuck on "_Syncing the lightning node to the blockchain_" and I get the following output:

```
> zap-desktop@0.0.1 dev /Users/mariodian/Github/zap-desktop
> cross-env START_HOT=1 concurrently "npm run start-renderer-dev"

[0]
[0] > zap-desktop@0.0.1 start-renderer-dev /Users/mariodian/Github/zap-desktop
[0] > cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js
[0]
[0] Starting Main Process...
[0] Project is running at http://localhost:1212/
[0] webpack output is served from http://localhost:1212/dist
[0] Content not from webpack is served from /Users/mariodian/Github/zap-desktop/dist
[0] 404s will fallback to /index.html
[0]
[0] > zap-desktop@0.0.1 start-main-dev /Users/mariodian/Github/zap-desktop
[0] > cross-env HOT=1 NODE_ENV=development electron -r babel-register ./app/main.dev
[0]
[0] Failed to read content scripts { Error: EACCES: permission denied, open '/Users/mariodian/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
[0]     at Object.fs.openSync (fs.js:584:18)
[0]     at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
[0]     at Object.fs.readFileSync (fs.js:491:33)
[0]     at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
[0]     at readArrayOfFiles (/Users/mariodian/Github/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:235:23)
[0]     at Array.map (native)
[0]     at contentScriptToEntry (/Users/mariodian/Github/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:242:21)
[0]     at Array.map (native)
[0]     at injectContentScripts (/Users/mariodian/Github/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:250:48)
[0]     at loadExtension (/Users/mariodian/Github/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:279:3)
[0]   errno: -13,
[0]   code: 'EACCES',
[0]   syscall: 'open',
[0]   path: '/Users/mariodian/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
[0] icon:  /Users/mariodian/Github/zap-desktop/resources/icon.icns
[0] 2017-12-29 18:56:04.696 Electron[60559:2635940] *** WARNING: Textured window <AtomNSWindow: 0x7fccc4dd8820> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
[0] 2017-12-29 18:56:05.817 [INF] LTND: Version 0.3.0-alpha
[0]
[0] 2017-12-29 18:56:05.865 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
[0]
[0] 2017-12-29 18:56:05.896 [INF] LTND: Primary chain is set to: bitcoin
[0]
[0] Failed to read content scripts { Error: EACCES: permission denied, open '/Users/mariodian/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
[0]     at Object.fs.openSync (fs.js:584:18)
[0]     at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
[0]     at Object.fs.readFileSync (fs.js:491:33)
[0]     at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
[0]     at readArrayOfFiles (/Users/mariodian/Github/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:235:23)
[0]     at Array.map (native)
[0]     at contentScriptToEntry (/Users/mariodian/Github/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:242:21)
[0]     at Array.map (native)
[0]     at injectContentScripts (/Users/mariodian/Github/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:250:48)
[0]     at loadExtension (/Users/mariodian/Github/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:279:3)
[0]   errno: -13,
[0]   code: 'EACCES',
[0]   syscall: 'open',
[0]   path: '/Users/mariodian/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
[0] 2017-12-29 18:56:06.375 [DBG] CMGR: Attempting to connect to 165.227.7.29:18333 (reqid 1)
[0]
[0] 2017-12-29 18:56:06.489 [DBG] CMGR: Attempting to connect to 207.154.242.226:18333 (reqid 2)
[0]
[0] 2017-12-29 18:56:06.549 [INF] BTCN: Loaded 1052 addresses from file '/Users/mariodian/Library/Application Support/Lnd/data/testnet3/bitcoin/peers.json'
[0]
[0] 2017-12-29 18:56:06.549 [DBG] CMGR: Connected to 165.227.7.29:18333 (reqid 1)
[0]
[0] 2017-12-29 18:56:06.557 Electron Helper[60565:2636117] Couldn't set selectedTextBackgroundColor from default ()
[0] 2017-12-29 18:56:06.558 [DBG] BTCN: Sending version (agent /btcwire:0.5.0/neutrino:0.0.1-alpha/, pver 70013, block 700000) to 165.227.7.29:18333 (outbound)
[0]
[0] 2017-12-29 18:56:06.732 [DBG] BTCN: Received version (agent /btcwire:0.5.0/btcd:0.12.0/, pver 70013, block 1256698) from 165.227.7.29:18333 (outbound)
[0] 2017-12-29 18:56:06.732 [DBG] BTCN: Negotiated protocol version 70013 for peer 165.227.7.29:18333 (outbound)
[0]
[0] 2017-12-29 18:56:06.733 [DBG] BTCN: Added time sample of 0s (total: 1)
[0] 2017-12-29 18:56:06.733 [DBG] BTCN: Connected to 165.227.7.29:18333
[0] 2017-12-29 18:56:06.733 [INF] BTCN: New valid peer 165.227.7.29:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)
[0]
[0] 2017-12-29 18:56:06.733 [DBG] BTCN: New peer 165.227.7.29:18333 (outbound)
[0] 2017-12-29 18:56:06.734 [DBG] BTCN: Sending verack to 165.227.7.29:18333 (outbound)
[0]
[0] 2017-12-29 18:56:06.740 [DBG] BTCN: Received verack from 165.227.7.29:18333 (outbound)
[0]
[0] 2017-12-29 18:56:06.742 [INF] BTCN: Syncing to block height 1256698 from peer 165.227.7.29:18333
[0]
[0] 2017-12-29 18:56:06.743 [INF] BTCN: Downloading headers for blocks 700001 to 800010 from peer 165.227.7.29:18333
[0]
[0] 2017-12-29 18:56:06.744 [DBG] BTCN: Sending getheaders (locator 000000000000406178b12a4dea3b27e13b3c4fe4510994fd667d7c1e6a3f4dc1, stop 000000000017ed35296433190b6829db01e657d80631d43f5983fa403bfdb4c1) to 165.227.7.29:18333 (outbound)
[0]
[0] 2017-12-29 18:56:06.811 [DBG] CMGR: Connected to 207.154.242.226:18333 (reqid 2)
[0]
[0] 2017-12-29 18:56:06.812 [DBG] BTCN: Sending version (agent /btcwire:0.5.0/neutrino:0.0.1-alpha/, pver 70013, block 700000) to 207.154.242.226:18333 (outbound)
[0]
[0] 2017-12-29 18:56:06.896 [INF] CMGR: 3 addresses found from DNS seed testnet-seed.bluematt.me
[0]
[0] 2017-12-29 18:56:06.902 [INF] CMGR: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org: no such host
[0]
[0] 2017-12-29 18:56:07.181 [DBG] BTCN: Received version (agent /btcwire:0.5.0/btcd:0.12.0/, pver 70013, block 1256698) from 207.154.242.226:18333 (outbound)
[0]
[0] 2017-12-29 18:56:07.181 [DBG] BTCN: Negotiated protocol version 70013 for peer 207.154.242.226:18333 (outbound)
[0]
[0] 2017-12-29 18:56:07.196 [DBG] BTCN: Added time sample of -1s (total: 2)
[0] 2017-12-29 18:56:07.196 [DBG] BTCN: Connected to 207.154.242.226:18333
[0] 2017-12-29 18:56:07.196 [INF] BTCN: New valid peer 207.154.242.226:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)
[0]
[0] 2017-12-29 18:56:07.196 [DBG] BTCN: Received verack from 207.154.242.226:18333 (outbound)
[0] 2017-12-29 18:56:07.196 [DBG] BTCN: New peer 207.154.242.226:18333 (outbound)
[0] 2017-12-29 18:56:07.196 [DBG] BTCN: Sending verack to 207.154.242.226:18333 (outbound)
[0]
[0] 2017-12-29 18:56:07.425 [DBG] BTCN: Received headers (num 2000) from 165.227.7.29:18333 (outbound)
[0]
[0] 2017-12-29 18:56:07.464 [DBG] BTCN: Difficulty retarget at block height 701568
[0] 2017-12-29 18:56:07.464 [DBG] BTCN: Old target 1b027904 (0000000000027904000000000000000000000000000000000000000000000000)
[0] 2017-12-29 18:56:07.464 [DBG] BTCN: New target 1b009e41 (0000000000009e41000000000000000000000000000000000000000000000000)
[0] 2017-12-29 18:56:07.464 [DBG] BTCN: Actual timespan 21h53m25s, adjusted timespan 84h0m0s, target timespan 336h0m0s
[0]
[0] 2017-12-29 18:56:08.027 [DBG] BTCN: Sending getcfheaders to 165.227.7.29:18333 (outbound)
[0] 2017-12-29 18:56:08.027 [DBG] BTCN: Sending getcfheaders to 207.154.242.226:18333 (outbound)
[0]
[0] 2017-12-29 18:56:08.027 [DBG] BTCN: Sending getcfheaders to 207.154.242.226:18333 (outbound)
[0] 2017-12-29 18:56:08.027 [DBG] BTCN: Sending getcfheaders to 165.227.7.29:18333 (outbound)
[0]
[0] 2017-12-29 18:56:08.028 [DBG] BTCN: Sending getheaders (locator 00000000000088687174912347c38e879d8d559679aef56eac8e053efb77a3e5, stop 000000000017ed35296433190b6829db01e657d80631d43f5983fa403bfdb4c1) to 165.227.7.29:18333 (outbound)
[0]
[0] 2017-12-29 18:56:08.047 [INF] CMGR: DNS discovery failed on seed x49.testnet-seed.bitcoin.jonasschnelli.ch: lookup x49.testnet-seed.bitcoin.jonasschnelli.ch: no such host
[0]
[0] unable to create wallet controller: invalid passphrase for master public key
[0] unable to create chain control: invalid passphrase for master public key
[0]
[0] lnd shutting down 1
[0] SENDING SYNCING
```

I can run lnd separately with no issues (but Zap still doesn't load) but when I only run Zap on its own it gives me these two errors:

```
unable to create wallet controller: invalid passphrase for master public key
unable to create chain control: invalid passphrase for master public key
```

**Comment by JimmyMow** [comment]
@mariodian are you still seeing issues here? This is strange, I've had no luck reproducing this.

What OS are you running anf what Zap/LND commits?

**Comment by mariodian** [comment]
Yes, I still have the issues.

I use the latest OSX 10.13.2. 

LND commit is #e2fe4c2, ZAP #6a1e069.

When I run zap (without running LND manually first) I'm getting the above error. 

When I run lnd manually first (from its own repo) and then zap, I'm able to open the app and click through tabs (Wallet, Peers, Channels and Network) but it's stuck on loading.

![screen shot 2018-01-06 at 2 50 45 am](https://user-images.githubusercontent.com/3636406/34623458-6ac3984e-f28c-11e7-85a1-bb1f0c807a44.png)

Also, I'm getting the following error:

```
> zap-desktop@0.0.1 dev /Users/mariodian/Source/Lightning/zap-desktop
> cross-env START_HOT=1 concurrently "npm run start-renderer-dev"

[0]
[0] > zap-desktop@0.0.1 start-renderer-dev /Users/mariodian/Source/Lightning/zap-desktop
[0] > cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js
[0]
[0] Starting Main Process...
[0] Project is running at http://localhost:1212/
[0] webpack output is served from http://localhost:1212/dist
[0] Content not from webpack is served from /Users/mariodian/Source/Lightning/zap-desktop/dist
[0] 404s will fallback to /index.html
[0]
[0] > zap-desktop@0.0.1 start-main-dev /Users/mariodian/Source/Lightning/zap-desktop
[0] > cross-env HOT=1 NODE_ENV=development electron -r babel-register ./app/main.dev
[0]
[0] Failed to read content scripts { Error: EACCES: permission denied, open '/Users/mariodian/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
[0]     at Object.fs.openSync (fs.js:584:18)
[0]     at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
[0]     at Object.fs.readFileSync (fs.js:491:33)
[0]     at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
[0]     at readArrayOfFiles (/Users/mariodian/Source/Lightning/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:235:23)
[0]     at Array.map (native)
[0]     at contentScriptToEntry (/Users/mariodian/Source/Lightning/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:242:21)
[0]     at Array.map (native)
[0]     at injectContentScripts (/Users/mariodian/Source/Lightning/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:250:48)
[0]     at loadExtension (/Users/mariodian/Source/Lightning/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:279:3)
[0]   errno: -13,
[0]   code: 'EACCES',
[0]   syscall: 'open',
[0]   path: '/Users/mariodian/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
[0] icon:  /Users/mariodian/Source/Lightning/zap-desktop/resources/icon.icns
[0] 2018-01-06 02:46:05.602 Electron[16835:2120586] *** WARNING: Textured window <AtomNSWindow: 0x7fcf925f4d30> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
[0] LND ALREADY RUNNING
[0] subscribeChannelGraph is happening
[0] E0106 02:46:06.529829000 140735598281536 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
[0] channelgraph error:  { Error: Connect Failed
[0]     at ClientReadableStream._emitStatusIfDone (/Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:255:19)
[0]     at ClientReadableStream._readsDone (/Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:221:8)
[0]     at readCallback (/Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:283:12) code: 14, metadata: Metadata { _internal_repr: {} } }
[0] error:  { Error: Connect Failed
[0]     at ClientReadableStream._emitStatusIfDone (/Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:255:19)
[0]     at ClientReadableStream._readsDone (/Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:221:8)
[0]     at readCallback (/Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:283:12) code: 14, metadata: Metadata { _internal_repr: {} } }
[0] status:  { code: 14,
[0]   details: 'Connect Failed',
[0]   metadata: Metadata { _internal_repr: {} } }
[0] error:  { Error: Connect Failed
[0]     at ClientReadableStream._emitStatusIfDone (/Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:255:19)
[0]     at ClientReadableStream._readsDone (/Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:221:8)
[0]     at readCallback (/Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:283:12) code: 14, metadata: Metadata { _internal_repr: {} } }
[0] TRANSACTION STATUS:  { code: 14,
[0]   details: 'Connect Failed',
[0]   metadata: Metadata { _internal_repr: {} } }
[0] Failed to read content scripts { Error: EACCES: permission denied, open '/Users/mariodian/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
[0]     at Object.fs.openSync (fs.js:584:18)
[0]     at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
[0]     at Object.fs.readFileSync (fs.js:491:33)
[0]     at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
[0]     at readArrayOfFiles (/Users/mariodian/Source/Lightning/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:235:23)
[0]     at Array.map (native)
[0]     at contentScriptToEntry (/Users/mariodian/Source/Lightning/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:242:21)
[0]     at Array.map (native)
[0]     at injectContentScripts (/Users/mariodian/Source/Lightning/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:250:48)
[0]     at loadExtension (/Users/mariodian/Source/Lightning/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:279:3)
[0]   errno: -13,
[0]   code: 'EACCES',
[0]   syscall: 'open',
[0]   path: '/Users/mariodian/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
[0] 2018-01-06 02:46:07.534 Electron Helper[16840:2120777] Couldn't set selectedTextBackgroundColor from default ()
[0] E0106 02:46:26.512168000 140735598281536 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
[0] transactions error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] invoices error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] payments error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] balance error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] newaddress error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] transactions error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] invoices error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] payments error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] balance error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] newaddress error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] E0106 02:46:46.512281000 140735598281536 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
[0] E0106 02:47:06.514311000 140735598281536 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
[0] E0106 02:47:26.514046000 140735598281536 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
[0] E0106 02:47:46.517076000 140735598281536 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
[0] E0106 02:48:06.518023000 140735598281536 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
[0] describeGraph error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] channels error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] peers error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] peers error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] channels error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] peers error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] E0106 02:48:26.713587000 140735598281536 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
[0] transactions error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] invoices error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] payments error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] balance error:  { Error: Connect Failed
[0]     at /Users/mariodian/Source/Lightning/zap-desktop/app/node_modules/grpc/src/client.js:554:15 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] E0106 02:48:53.838773000 140735598281536 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
```

**Comment by JimmyMow** [comment]
Hm, Zap is not able to establish a connection to your node due to SSL errors. 

Try removing the `tls.cert` and `tls.key` in your `Lnd` directory. Looks like you have bad certs

**Comment by mariodian** [comment]
Thanks, removing tls.cert and tls.key helped. However, I have to run lnd separately (which is not a big deal), running it from resources/bin/darwin/ still gives me the following error: 

```
unable to create wallet controller: invalid passphrase for master public key
unable to create chain control: invalid passphrase for master public key
```
