### ISSUE TITLE
npm run dev - Dependancy Issues?

### ISSUE THREAD

**Issue by Haafingar** [LN-Zap/zap-desktop#17]
Hi everyone,
I have a fully synced segwit BTCD node up with LND, and building this on Ubuntu 17.04. I used npm to install dependencies ( I know it said to use yarn, but I was having problems with installing yarn so I stuck with npm instead). Npm generated the following log after I ran npm run dev.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle zap-desktop@0.0.1~predev: zap-desktop@0.0.1
6 info lifecycle zap-desktop@0.0.1~dev: zap-desktop@0.0.1
7 verbose lifecycle zap-desktop@0.0.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle zap-desktop@0.0.1~dev: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/tempest/zap-desktop/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle zap-desktop@0.0.1~dev: CWD: /home/tempest/zap-desktop
10 silly lifecycle zap-desktop@0.0.1~dev: Args: [ '-c', 'cross-env START_HOT=1 npm run start-renderer-dev' ]
11 silly lifecycle zap-desktop@0.0.1~dev: Returned: code: 1  signal: null
12 info lifecycle zap-desktop@0.0.1~dev: Failed to exec dev script
13 verbose stack Error: zap-desktop@0.0.1 dev: `cross-env START_HOT=1 npm run start-renderer-dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid zap-desktop@0.0.1
15 verbose cwd /home/tempest/zap-desktop
16 verbose Linux 4.10.0-33-generic
17 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error zap-desktop@0.0.1 dev: `cross-env START_HOT=1 npm run start-renderer-dev`
22 error Exit status 1
23 error Failed at the zap-desktop@0.0.1 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Admittedly I'm quite new to this, but any suggestions for next steps would be greatly appreciated.

**Comment by callmekurisu** [comment]
what version npm do you have?

**Comment by jackmallers** [comment]
You are also not supposed to use both NPM and yarn, you should pick one or the other. If you installed some dependencies with yarn and others with npm the application will throw errors

**Comment by jackmallers** [comment]
Any update on this? Closing for now

**Comment by Haafingar** [comment]
Apolagies jack, been away. I have only used npm to handle dependancies. Cloned to a new folder and reinstalled only using npm 5.4.1 just to make sure. Another debug log in case it's useful is attached.

[2017-09-15T00_22_41_543Z-debug.log.zip](https://github.com/LN-Zap/zap-desktop/files/1304938/2017-09-15T00_22_41_543Z-debug.log.zip)
