### ISSUE TITLE
"Endpoint read failed" Javascript Error when connection to LND is lost bug

### ISSUE THREAD

**Issue by helgabutters** [LN-Zap/zap-desktop#207]
I think this error happens when you kill `lnd` while Zap is currently talking with `lnd`. During my testing with #205 and #206 I was killing `lnd` at different points to see the response and this error popped up on three random occasions.

### Error Log:

```
[0] status:  { code: 0,
[0]   details: '',
[0]   metadata: Metadata { _internal_repr: {} } }
[0] end
[0] error:  { Error: Endpoint read failed
[0]     at ClientReadableStream._emitStatusIfDone (/home/pnd/zap-desktop/app/node_modules/grpc/src/client.js:255:19)
[0]     at ClientReadableStream._receiveStatus (/home/pnd/zap-desktop/app/node_modules/grpc/src/client.js:233:8)
[0]     at /home/pnd/zap-desktop/app/node_modules/grpc/src/client.js:705:12 code: 14, metadata: Metadata { _internal_repr: {} } }
[0] TRANSACTION STATUS:  { code: 14,
[0]   details: 'Endpoint read failed',
[0]   metadata: Metadata { _internal_repr: {} } }
```

### Screenshot:
![uncaughtexception](https://user-images.githubusercontent.com/8001978/35138126-00756dc6-fcbb-11e7-8beb-a1653be2b6b7.png)

**Comment by JimmyMow** [comment]
Yeah so this is unexpected behavior, if LND gets killed then Zap obviously won't work.

Curious what you'd expect to see UX wise? Right now we don't do anything, we just let LND die

**Comment by helgabutters** [comment]
My thought at this point would be on a timeout/unsuccessful connection, present the red error message box at the top of the UI. Simple suggestion for now on wording would be "Backend connection failed. Retrying in X sec" where X would be whatever value is currently used (or not) for the retry.

**Comment by mrfelton** [comment]
Handling for if/when Lnd crashes was updated in 0.4.x to provide feedback to the user, present the error message, and send the user back to the launchpad area.
