### ISSUE TITLE
Zap doesn't recreate directories if removed

### ISSUE THREAD

**Issue by langenoja** [LN-Zap/zap-desktop#319]
I tried mounting my local servers lnd instance into my ubuntu desktop user to see if that would work to have my config for LND running like that. It didn't, and in the process I removed the .lnd directory. The following error is shown upon starting the zap appimage now.

Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/galactica/.lnd/admin.macaroon'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at t.default (/tmp/.mount_zap-deexEjVJ/app/resources/app.asar/webpack:/app/lnd/index.js:13:3)
    at P (/tmp/.mount_zap-deexEjVJ/app/resources/app.asar/webpack:/app/main.dev.js:116:33)
    at /tmp/.mount_zap-deexEjVJ/app/resources/app.asar/webpack:/app/main.dev.js:284:3
    at /tmp/.mount_zap-deexEjVJ/app/resources/app.asar/node_modules/ps-node/lib/index.js:183:7
    at ChildProcess.<anonymous> (/tmp/.mount_zap-deexEjVJ/app/resources/app.asar/node_modules/ps-node/lib/index.js:97:9)
    at emitTwo (events.js:106:13)

**Comment by langenoja** [comment]
It is apparent that I didn't really read the readme before embarking on this, but I'll leave it in.
