### ISSUE TITLE
Unhandled React exception

### ISSUE THREAD

**Issue by ALongshot** [LN-Zap/zap-desktop#3195]
Detailed Description
-------
``TypeError: Cannot read property 'color' of undefined
    at http://localhost:3100/renderer.js:318:961665
    at ix (http://localhost:3100/renderer.js:318:961779)
    at fa (http://localhost:3100/renderer.js:42:59532)
    at xs (http://localhost:3100/renderer.js:42:104763)
    at Ic (http://localhost:3100/renderer.js:42:90342)
    at Pc (http://localhost:3100/renderer.js:42:90267)
    at wc (http://localhost:3100/renderer.js:42:87607)
    at http://localhost:3100/renderer.js:42:45937
    at t.unstable_runWithPriority (http://localhost:3100/renderer.js:50:3465)
    at Kr (http://localhost:3100/renderer.js:42:45646)``
        
Your Environment
----
- Zap version: Zap 0.6.0-beta

**Comment by mrfelton** [comment]
Hi @ALongshot . Do you remember what you were doing right before you got this error? Thanks!
