### ISSUE TITLE
Unhandled React exception

### ISSUE THREAD

**Issue by elkimek** [LN-Zap/zap-desktop#3197]
Detailed Description
-------
``TypeError: toBitcoin must be called on a whole number or string format whole number
    at Object.toBitcoin (http://localhost:3100/renderer.js:66:61329)
    at f (http://localhost:3100/renderer.js:318:2147609)
    at b (http://localhost:3100/renderer.js:318:2147740)
    at w (http://localhost:3100/renderer.js:318:2148506)
    at ls (http://localhost:3100/renderer.js:318:29117)
    at fa (http://localhost:3100/renderer.js:42:59532)
    at Za (http://localhost:3100/renderer.js:42:67748)
    at xs (http://localhost:3100/renderer.js:42:105936)
    at Ic (http://localhost:3100/renderer.js:42:90342)
    at Pc (http://localhost:3100/renderer.js:42:90267)``
        
Your Environment
----
- Zap version: Zap 0.6.0-beta

**Comment by mrfelton** [comment]
Hi, please can you update to 0.6.2. Thanks

**Comment by elkimek** [comment]
Ok thanks!

**Comment by mrfelton** [comment]
Also, could you tell me what you were doing right before you got this error please? Thanks!

**Comment by elkimek** [comment]
Was just sweeping off my onchain funds b/c of BTCPay upgrade. Couldn't make the transaction.

**Comment by mrfelton** [comment]
Ahh I see, and is it working now for you with 0.6.2?

**Comment by elkimek** [comment]
Can't tell, used RTL for the sweeping :)

**Comment by mrfelton** [comment]
I believe this issue to be resolved in `next` branch in which all of the number handling has been revamped to use BigNumber for currency conversions. Fix will be included in next release.
