### ISSUE TITLE
Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.

### ISSUE THREAD

**Issue by Empact** [LN-Zap/zap-desktop#324]
This is with the current master of Lnd, as run by Zap.

```
CERT EXISTS, STARTING GRPC
[0] E0307 18:10:13.136523000 140735655744320 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
[0] error:  { Error: Connect Failed
[0]     at ClientReadableStream._emitStatusIfDone (/Users/ben/Development/Bitcoin/zap-desktop/app/node_modules/grpc/src/client.js:255:19)
[0]     at ClientReadableStream._readsDone (/Users/ben/Development/Bitcoin/zap-desktop/app/node_modules/grpc/src/client.js:221:8)
[0]     at readCallback (/Users/ben/Development/Bitcoin/zap-desktop/app/node_modules/grpc/src/client.js:283:12) code: 14, metadata: Metadata { _internal_repr: {} } }
[0] status:  { code: 14,
[0]   details: 'Connect Failed',
[0]   metadata: Metadata { _internal_repr: {} } }
[0] error:  { Error: Connect Failed
[0]     at ClientReadableStream._emitStatusIfDone (/Users/ben/Development/Bitcoin/zap-desktop/app/node_modules/grpc/src/client.js:255:19)
[0]     at ClientReadableStream._readsDone (/Users/ben/Development/Bitcoin/zap-desktop/app/node_modules/grpc/src/client.js:221:8)
[0]     at readCallback (/Users/ben/Development/Bitcoin/zap-desktop/app/node_modules/grpc/src/client.js:283:12) code: 14, metadata: Metadata { _internal_repr: {} } }
[0] TRANSACTION STATUS:  { code: 14,
[0]   details: 'Connect Failed',
[0]   metadata: Metadata { _internal_repr: {} } }
[0] 2018-03-07 18:10:13.161 [DBG] BTCN: waiting to see if more peers will respond with cfheaders
```

**Comment by Empact** [comment]
Here's a temp workaround from @jackmallers:
```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'
process.env.GRPC_SSL_CIPHER_SUITES = 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384'
```

**Comment by JimmyMow** [comment]
@Empact yeah working for me locally on my `cipherseed` restore/backup seed branch I will push up tonight.

Just need to set those env variables before you read the cert and establish the `grpc` connection
