### ISSUE TITLE
Unhandled React exception -- due to LND 0.9.0 KEYSEND tip payment received 

### ISSUE THREAD

**Issue by beeforbacon** [LN-Zap/zap-desktop#3333]
Detailed Description --- clicking the keysend payment crashes ZAP. I know this is a new feature but wanted to make an issue on it. Thanks! 
-------
``Error: Not a proper lightning payment request
    at Object.decode (file:///tmp/.mount_Zap-liXBYKdZ/resources/app.asar/dist/renderer.js:14:299788)
    at b (file:///tmp/.mount_Zap-liXBYKdZ/resources/app.asar/dist/renderer.js:318:2150463)
    at file:///tmp/.mount_Zap-liXBYKdZ/resources/app.asar/dist/renderer.js:318:971849
    at Object.useMemo (file:///tmp/.mount_Zap-liXBYKdZ/resources/app.asar/dist/renderer.js:42:63699)
    at useMemo (file:///tmp/.mount_Zap-liXBYKdZ/resources/app.asar/dist/renderer.js:66:5264)
    at Dx (file:///tmp/.mount_Zap-liXBYKdZ/resources/app.asar/dist/renderer.js:318:971832)
    at fa (file:///tmp/.mount_Zap-liXBYKdZ/resources/app.asar/dist/renderer.js:42:59532)
    at xs (file:///tmp/.mount_Zap-liXBYKdZ/resources/app.asar/dist/renderer.js:42:104763)
    at Ic (file:///tmp/.mount_Zap-liXBYKdZ/resources/app.asar/dist/renderer.js:42:90342)
    at Pc (file:///tmp/.mount_Zap-liXBYKdZ/resources/app.asar/dist/renderer.js:42:90267)``
        
Your Environment
----
- Zap version: Zap 0.6.2-beta

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3393
