### ISSUE TITLE
Unhandled React exception

### ISSUE THREAD

**Issue by klauslovgreen** [LN-Zap/zap-desktop#3588]
Detailed Description
-------
``Error: Not a proper lightning payment request
    at Object.decode (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:14:299788)
    at b (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:318:2150463)
    at file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:318:971849
    at Object.useMemo (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:42:63699)
    at useMemo (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:66:5264)
    at Dx (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:318:971832)
    at fa (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:42:59532)
    at xs (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:42:104763)
    at Ic (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:42:90342)
    at Pc (file:///Applications/Zap.app/Contents/Resources/app.asar/dist/renderer.js:42:90267)``
        
Your Environment
----
- Zap version: Zap 0.6.2-beta

**Comment by mrfelton** [comment]
Hi, can you share the payment request you were trying to use please?

**Comment by klauslovgreen** [comment]
Hi,

When I open the Zap wallet and click on an payment from the list of
transactions - I get this:


[image: Screen Shot 2020-06-29 at 13.16.34.png]

[image: Screen Shot 2020-06-29 at 13.18.45.png]

**Comment by mrfelton** [comment]
Is the payment a `keysend` payment by any chance?

Can you try with a build from the `master` branch please?

**Comment by klauslovgreen** [comment]
Yes it is a keysend - (Sphinx.chat)

"Can you try with a build from the master branch please?"

How do I do that?


--

*Klaus Lovgreen*

(+33) 680 865 167
www.evershift.com

**Comment by mrfelton** [comment]
```
git clone git@github.com:LN-Zap/zap-desktop.git
cd zap-desktop
yarn
yarn package
```

That will build a version of 0.7.0-beta into the `release` directory.

https://github.com/LN-Zap/zap-desktop/blob/master/docs/ADVANCED.md#compiling-zap-from-source

**Comment by klauslovgreen** [comment]
I run the Mac and iOS version of Zap in connection with a MyNode setup

--

*Klaus Lovgreen*

(+33) 680 865 167
www.evershift.com

**Comment by mrfelton** [comment]
Please can you confirm if this is still an issue with [Zap 0.7.0](https://github.com/LN-Zap/zap-desktop/releases/tag/v0.7.0-beta). Thanks!

**Comment by klauslovgreen** [comment]
Hey Tom,

Yes confirmed all looks great now - all transactions show details.

Awesome work!

Cheers,
Klaus

--

*Klaus Lovgreen*

(+33) 680 865 167
www.evershift.com

**Comment by mrfelton** [comment]
Great, thanks for confirming.
