### ISSUE TITLE
Race condition on shutdown between LND and App

### ISSUE THREAD

**Issue by Empact** [LN-Zap/zap-desktop#586]
Here's the evidence I have for it - closed the app and a transient error box displayed before it closed.

```
  zap:main [INF]  Sending message to renderer process: { msg: 'startOnboarding', data: undefined } +2m
  zap:main [INF]  Lnd process has shut down (code null) +2s
  zap:main [ERR]  error:  Error: 2 UNKNOWN: Stream removed
  zap:main ___Stack trace #1___
  zap:main Error: 2 UNKNOWN: Stream removed
  zap:main     at Object.exports.createStatusError (/Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/common.js:87:15)
  zap:main     at ClientReadableStream._emitStatusIfDone (/Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/client.js:235:26)
  zap:main     at ClientReadableStream._receiveStatus (/Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/client.js:213:8)
  zap:main     at Object.onReceiveStatus (/Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/client_interceptors.js:1256:15)
  zap:main     at InterceptingListener._callNext (/Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/client_interceptors.js:564:42)
  zap:main     at InterceptingListener.onReceiveStatus (/Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/client_interceptors.js:614:8)
  zap:main     at /Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/client_interceptors.js:1019:24 +304ms
  zap:main [INF]  TRANSACTION STATUS:  [object Object]
  zap:main ___Inspected object #1___
  zap:main { code: 2,
  zap:main   details: 'Stream removed',
  zap:main   metadata: Metadata { _internal_repr: {} } } +1ms
  zap:main [ERR]  Error: 2 UNKNOWN: Stream removed
  zap:main ___Stack trace #1___
  zap:main Error: 2 UNKNOWN: Stream removed
  zap:main     at Object.exports.createStatusError (/Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/common.js:87:15)
  zap:main     at ClientReadableStream._emitStatusIfDone (/Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/client.js:235:26)
  zap:main     at ClientReadableStream._receiveStatus (/Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/client.js:213:8)
  zap:main     at Object.onReceiveStatus (/Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/client_interceptors.js:1256:15)
  zap:main     at InterceptingListener._callNext (/Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/client_interceptors.js:564:42)
  zap:main     at InterceptingListener.onReceiveStatus (/Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/client_interceptors.js:614:8)
  zap:main     at /Users/ben/Development/Zap/zap-desktop/app/node_modules/grpc/src/client_interceptors.js:1019:24 +4ms
  zap:main [INF]  status: [object Object]
  zap:main ___Inspected object #1___
  zap:main { code: 2,
  zap:main   details: 'Stream removed',
  zap:main   metadata: Metadata { _internal_repr: {} } } +0ms
✨  Done in 2564.71s.
```

**Comment by Empact** [comment]
Possibly related:
```
  zap:main [INF]  Sending message to renderer process: { msg: 'startOnboarding', data: undefined } +2s
2018-07-22 14:39:59.101 Electron Helper[44171:6984623] Couldn't set selectedTextBackgroundColor from default ()
TypeError: Cannot read property 'close' of undefined
    at state.then (/Users/ben/Development/Zap/zap-desktop/node_modules/webpack-serve/lib/app.js:71:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'close' of undefined
    at state.then (/Users/ben/Development/Zap/zap-desktop/node_modules/webpack-serve/lib/app.js:71:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zap-desktop@0.1.1 start-renderer-dev: `node --trace-warnings -r babel-register ./node_modules/webpack-serve/lib/cli.js --config webpack.config.renderer.dev.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zap-desktop@0.1.1 start-renderer-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ben/.npm/_logs/2018-07-22T18_40_00_251Z-debug.log
```

**Comment by mrfelton** [comment]
How did you close the app @Empact ?

 - close the window?
 - ctrl+q from electron?
 - ctrl+c from the terminal?
