### ISSUE TITLE
Failed to read content scripts Error: EACCES: permission denied

### ISSUE THREAD

**Issue by kyluke** [LN-Zap/zap-desktop#78]
After the setup with yarn, running ```npm run dev``` gets stuck at " 0% - syncing your lightning node to the blockchain".

The console outputs the following:

```
[0] Failed to read content scripts { Error: EACCES: permission denied, open '/Users/user/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
[0]     at Object.fs.openSync (fs.js:584:18)
[0]     at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
[0]     at Object.fs.readFileSync (fs.js:491:33)
[0]     at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
[0]     at readArrayOfFiles (/Users/user/code/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:233:23)
[0]     at Array.map (native)
[0]     at contentScriptToEntry (/Users/user/code/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:240:21)
[0]     at Array.map (native)
[0]     at injectContentScripts (/Users/user/code/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:248:48)
[0]     at loadExtension (/Users/user/code/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:277:3)
[0]   errno: -13,
[0]   code: 'EACCES',
[0]   syscall: 'open',
[0]   path: '/Users/user/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
[0] icon:  /Users/user/code/zap-desktop/resources/icon.icns
[0] 2017-11-23 09:02:44.227 Electron[98411:683864] *** WARNING: Textured window <AtomNSWindow: 0x7ffafceab6f0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
[0] lnd shutting down null
[0] Failed to read content scripts { Error: EACCES: permission denied, open '/Users/user/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
[0]     at Object.fs.openSync (fs.js:584:18)
[0]     at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
[0]     at Object.fs.readFileSync (fs.js:491:33)
[0]     at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
[0]     at readArrayOfFiles (/Users/user/code/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:233:23)
[0]     at Array.map (native)
[0]     at contentScriptToEntry (/Users/user/code/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:240:21)
[0]     at Array.map (native)
[0]     at injectContentScripts (/Users/user/code/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:248:48)
[0]     at loadExtension (/Users/user/code/zap-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:277:3)
[0]   errno: -13,
[0]   code: 'EACCES',
[0]   syscall: 'open',
[0]   path: '/Users/user/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
[0] 2017-11-23 09:02:46.397 Electron Helper[98416:684273] Couldn't set selectedTextBackgroundColor from default ()
```

The file exists:

```
-rw-r--r--  1 user  staff   327K Sep  1 18:20 backend.js
-rw-r--r--  1 user  staff   3.0K Sep  1 18:20 background.js
-rw-r--r--  1 user  staff   1.6K Sep  1 18:20 contentScript.js
-rwxrwxrwx  1 user  staff    10K Sep  1 18:20 inject.js
-rw-r--r--  1 user  staff   1.7K Sep  1 18:20 main.js
-rw-r--r--  1 user  staff   1.2M Sep  1 18:20 panel.js
```

Note, I gave ```inject.js``` 777 permission to try and see if that would fix it.

**Comment by JimmyMow** [comment]
Any update on this? Sorry for the late response

**Comment by kyluke** [comment]
Not yet, perhaps I'm not waiting long enough; how long does a sync usually take from scratch?

**Comment by joaodealmeida** [comment]
around 20 min

**Comment by victorbordo** [comment]
@kyluke I'm seeing the same issue on Mac OSX (Sierra 10.12.6). Try `chmod 744 build` where `inject.js` resides. I can also note that `sudo npm run dev` silences the err but it looks like the problem persists using that route. Also doesn't smell right to start up the process as root

**Comment by JimmyMow** [comment]
@victorbordo @kyluke did a little research and it looks like this issue stems from `electron-devtools-installer`: https://github.com/MarshallOfSound/electron-devtools-installer/pull/64

Zap just needs to update `electron-devtools-installer`. Doing that locally should solve the issue for you. I will create an issue and update `master` tonight

**Comment by JimmyMow** [comment]
closing this because of https://github.com/LN-Zap/zap-desktop/pull/91

feel free to re-open if this is still an issue
